---
- name: Install Galaxy
  hosts: localhost
  connection: local
  vars:
    NAMESPACE: galaxy
    PULSAR_URL: "{{ pulsar_ngrok_url }}"
    
    PULSAR_PATCH_URL: "https://raw.githubusercontent.com/jbernalr-iacs/tosca/main/files/pulsar.py"
    
    admin_users: "{{ galaxy_admin_users | default('admin@galaxy.com') }}"
    brand: "{{ galaxy_brand | default('IM Deployed Galaxy K8s Cluster') }}"
    max_mem: "{{ galaxy_max_mem | default(0) }}"
    max_cores: "{{ galaxy_max_cores | default(0) }}"
    galaxy_infra_url: "{{ galaxy_url | default('http://' ~ ansible_default_ipv4.address ~ '/galaxy') }}"
  tasks:

    - name: "Check if postgres-operator is already deployed"
      command: helm status postgres-operator -n {{ NAMESPACE }}
      register: deployed
      failed_when: deployed.rc != 0 and deployed.rc != 1
      changed_when: false
      environment:
        KUBECONFIG: /etc/kubernetes/admin.conf

    - when: deployed.rc == 1
      block:
        - name: Create postgres-operator helm chart values file
          copy:
            dest: /opt/postgres_values.yaml
            mode: '644'
            content: "{}"
        - name: Add helm repo cloudnative-pg
          command: helm repo add cloudnative-pg https://cloudnative-pg.github.io/charts/
          environment:
            KUBECONFIG: /etc/kubernetes/admin.conf
        - name: Deploy postgres-operator
          command: helm install -n {{ NAMESPACE }} --create-namespace postgres-operator cloudnative-pg/cloudnative-pg --version 0.23.2 -f /opt/postgres_values.yaml --wait
          environment:
            KUBECONFIG: /etc/kubernetes/admin.conf

    - name: "Check if rabbitmq-operator is already deployed"
      command: helm status rabbitmq-operator -n {{ NAMESPACE }}
      register: deployed
      failed_when: deployed.rc != 0 and deployed.rc != 1
      changed_when: false
      environment:
        KUBECONFIG: /etc/kubernetes/admin.conf

    - when: deployed.rc == 1
      block:
        - name: Create rabbitmq-operator helm chart values file
          copy:
            dest: /opt/rabbitmq_values.yaml
            mode: '644'
            content: |
              nameOverride: rabbitmq
              credentialUpdaterImage:
                repository: bitnamilegacy/rmq-default-credential-updater
              rabbitmqImage:
                repository: bitnamilegacy/rabbitmq
              clusterOperator:
                image:
                  repository: bitnamilegacy/rabbitmq-cluster-operator
              msgTopologyOperator:
                image:
                  repository: bitnamilegacy/rmq-messaging-topology-operator
        - name: Add helm repo bitnami
          command: helm repo add bitnami https://charts.bitnami.com/bitnami
          environment:
            KUBECONFIG: /etc/kubernetes/admin.conf
        - name: Deploy rabbitmq-operator
          command: helm install -n {{ NAMESPACE }} --create-namespace rabbitmq-operator bitnami/rabbitmq-cluster-operator --version  2.6.12 -f /opt/rabbitmq_values.yaml  --wait
          environment:
            KUBECONFIG: /etc/kubernetes/admin.conf

    - name: "Check if galaxy is already deployed"
      command: helm status galaxy -n {{ NAMESPACE }}
      register: deployed
      changed_when: false
      failed_when: deployed.rc != 0 and deployed.rc != 1
      environment:
        KUBECONFIG: /etc/kubernetes/admin.conf

    - when: deployed.rc == 1
      block:
        - name: Create Galaxy Namespace
          command: kubectl create namespace {{ NAMESPACE }}
          ignore_errors: yes
          environment:
            KUBECONFIG: /etc/kubernetes/admin.conf

        - name: Download Pulsar Patch from Custom Repo
          get_url:
            url: "{{ PULSAR_PATCH_URL }}"
            dest: /tmp/pulsar.py
            force: yes

        - name: Create Pulsar Patch ConfigMap
          shell: |
            kubectl create configmap galaxy-pulsar-patch \
            --from-file=pulsar.py=/tmp/pulsar.py \
            -n {{ NAMESPACE }} --dry-run=client -o yaml | kubectl apply -f -
          environment:
            KUBECONFIG: /etc/kubernetes/admin.conf

        - name: Remove GiB from max_mem
          set_fact:
            max_mem: "{{ max_mem[:-3] | float - 1 }}"
          when: max_mem and "GiB" in max_mem

        - name: Create galaxy helm chart values file
          copy:
            dest: /opt/galaxy_values.yaml
            mode: '644'
            content: |
              persistence:
                accessMode: ReadWriteMany
              s3csi:
                deploy: false
              cvmfs:
                deploy: false
              refdata:
                enabled: false
              postgresql:
                deploy: false
              rabbitmq:
                deploy: false
              
              configs:
                galaxy.yml:
                  galaxy:
                    admin_users: "{{ admin_users }}"
                    brand: "{{ brand }}"
                    galaxy_infrastructure_url: "{{ galaxy_infra_url }}"
                    sanitize_all_html: false
                
                job_conf.yml:
                  execution:
                    default: tpv_dispatcher
                    environments:
                      tpv_dispatcher:
                        container_monitor: false
                        docker_default_container_id: 'quay.io/galaxyproject/galaxy-min:24.2-uid'
                        function: map_tool_to_destination
                        rules_module: tpv.rules
                        runner: dynamic
                        tpv_config_files:
                          - https://gxy.io/tpv/db.yml
                          - /galaxy/server/database/rules/tpv_rules_local.yml
                        type: python
                  handling:
                    assign:
                      - db-skip-locked
                  destinations:
                    pulsar_eosc_node:
                      runner: pulsar_rest
                      params:
                        app: _default_
                        url: "{{ PULSAR_URL }}"
                        private_token: eucanscreen2026
                        # APUNTADO al mapa de acciones en el disco persistente
                        file_action_config: /galaxy/server/database/rules/pulsar_actions.yml
                        rewrite_parameters: true
                        dependency_resolution: remote
                        submit_native_python_path: true
                  runners:
                    k8s:
                      k8s_cleanup_job: onsuccess
                      k8s_data_volume_claim: 'galaxy-galaxy-pvc:/galaxy/server/database'
                      load: galaxy.jobs.runners.kubernetes:KubernetesJobRunner
                      k8s_use_service_account: true
                    local:
                      load: galaxy.jobs.runners.local:LocalJobRunner
                      workers: 4
                    pulsar_rest:
                      load: galaxy.jobs.runners.pulsar:PulsarJobRunner

              extraVolumeMounts:
                - name: pulsar-patch-volume
                  mountPath: /galaxy/server/lib/galaxy/jobs/runners/pulsar.py
                  subPath: pulsar.py
              
              extraVolumes:
                - name: pulsar-patch-volume
                  configMap:
                    name: galaxy-pulsar-patch

              jobs:
                rules:
                  tpv_rules_local.yml:
                    destinations:
                      k8s:
                        runner: k8s
                        {{ 'max_cores: ' ~ (max_cores | int - 1) if max_cores | int > 0 else '# no max_cores' }}
                        {{ 'max_mem: ' ~ max_mem if max_mem | int > 0 else '# no max_mem' }}
              
              tusd:
                ingress:
                  annotations:
                    nginx.ingress.kubernetes.io/connection-proxy-header: "keep-alive"
                    nginx.ingress.kubernetes.io/enable-websockets: "true"

        - name: Add helm repo galaxy
          command: helm repo add galaxy https://raw.githubusercontent.com/CloudVE/helm-charts/master/
          environment:
            KUBECONFIG: /etc/kubernetes/admin.conf

        - name: Deploy Galaxy
          command: helm install --create-namespace -n {{ NAMESPACE }} galaxy galaxy/galaxy --timeout 10m -f /opt/galaxy_values.yaml --version 6.6.0
          environment:
            KUBECONFIG: /etc/kubernetes/admin.conf

        - name: Create HTTPRoute manifest file for Galaxy
          copy:
            dest: /opt/galaxy_http_route.yaml
            mode: '644'
            content: |
              apiVersion: gateway.networking.k8s.io/v1
              kind: HTTPRoute
              metadata:
                name: galaxy-main-route
                namespace: {{ NAMESPACE }}
              spec:
                parentRefs:
                - name: nginx-gateway
                  namespace: nginx-gateway
                  sectionName: http
                rules:
                - matches:
                  - path:
                      type: PathPrefix
                      value: /
                  backendRefs:
                  - name: galaxy-nginx
                    port: 8000

        - name: Apply HTTPRoute to open Nginx Gateway
          command: kubectl apply -f /opt/galaxy_http_route.yaml
          environment:
            KUBECONFIG: /etc/kubernetes/admin.conf

        - name: Wait Galaxy Web to be available
          command: kubectl -n {{ NAMESPACE }} wait --for=condition=Available deployment/galaxy-web --timeout=600s
          environment:
            KUBECONFIG: /etc/kubernetes/admin.conf
          ignore_errors: true

        - name: Delete Pending stuck pods (CreateContainerConfigError)
          shell: kubectl get pods -n {{ NAMESPACE }} -o jsonpath='{range .items[?(@.status.containerStatuses[0].state.waiting.reason=="CreateContainerConfigError")]}{.metadata.namespace} {.metadata.name}{"\n"}{end}' | xargs -r -n2 sh -c 'kubectl delete pod $1 -n $0'
          register: error_pods
          changed_when: error_pods.stdout_lines | length > 1
          retries: 5
          delay: 120
          until: error_pods.stdout_lines | length < 1
          environment:
            KUBECONFIG: /etc/kubernetes/admin.conf

        - name: Generate local Pulsar Actions file
          copy:
            dest: /tmp/pulsar_actions.yml
            mode: '644'
            content: |
              default_action: transfer
              paths:
                - action: transfer
                  type: jobdir
                - action: transfer
                  prefix: /galaxy/server/database

        - name: Generate local TPV Rules file (Injecting Ngrok URL)
          copy:
            dest: /tmp/tpv_rules_local.yml
            mode: '644'
            content: |
              global:
                default_inherits: default
              destinations:
                pulsar_eosc_node:
                  runner: pulsar_rest
                  params:
                    file_action_config: /galaxy/server/database/rules/pulsar_actions.yml
                    rewrite_parameters: 'true'
                    dependency_resolution: remote
                    # [MAGIA IAC] Aquí Ansible inyecta la variable automáticamente
                    url: {{ PULSAR_URL }}
                    private_token: eucanscreen2026
                  scheduling:
                    require: [pulsar_ngrok_tunnel]
                k8s:
                  runner: k8s
                  max_cores: 1
                  params:
                    docker_enabled: 'true'
                  scheduling:
                    accept: [docker]
              tools:
                upload1:
                  execute: k8s
                __DATA_FETCH__:
                  execute: k8s
                default:
                  params:
                    container_monitor: false
                    docker_default_container_id: quay.io/galaxyproject/galaxy-min:24.2-uid
                    tmp_dir: 'true'
                  scheduling:
                    reject: [offline]
                '.*ecs_fetch_aspire.*':
                  scheduling:
                    require: [pulsar_ngrok_tunnel]
                '.*ecs_enrich_v2.*':
                  scheduling:
                    require: [pulsar_ngrok_tunnel]
                '.*ecs_qc.*':
                  scheduling:
                    require: [pulsar_ngrok_tunnel]
                '.*ecs_merge.*':
                  execute: k8s
                '.*ecs_dashboard.*':
                  execute: k8s

        - name: Get active galaxy-job-0 pod name
          shell: "kubectl get pods -n {{ NAMESPACE }} | grep '^galaxy-job-0' | grep 'Running' | awk '{print $1}' | head -n 1"
          register: job_pod_name
          retries: 10
          delay: 15
          until: job_pod_name.stdout != ""
          environment:
            KUBECONFIG: /etc/kubernetes/admin.conf

        - name: Create rules directory in Galaxy Persistent Volume
          command: kubectl exec {{ job_pod_name.stdout }} -n {{ NAMESPACE }} -- mkdir -p /galaxy/server/database/rules
          environment:
            KUBECONFIG: /etc/kubernetes/admin.conf

        - name: Copy Pulsar Actions into the Persistent Volume
          command: kubectl cp /tmp/pulsar_actions.yml {{ NAMESPACE }}/{{ job_pod_name.stdout }}:/galaxy/server/database/rules/pulsar_actions.yml
          environment:
            KUBECONFIG: /etc/kubernetes/admin.conf

        - name: Copy TPV Rules into the Persistent Volume
          command: kubectl cp /tmp/tpv_rules_local.yml {{ NAMESPACE }}/{{ job_pod_name.stdout }}:/galaxy/server/database/rules/tpv_rules_local.yml
          environment:
            KUBECONFIG: /etc/kubernetes/admin.conf

        - name: Cleanup temporary local rule files
          file:
            path: "{{ item }}"
            state: absent
          loop:
            - /tmp/pulsar_actions.yml
            - /tmp/tpv_rules_local.yml

